name: logging_handlers
version: 0.6.1
authors: 
  Chris Buckett <chrisbuckett@gmail.com>
  Günter Zöchbauer <guenter@gzoechbauer.com>
description: A selection of handlers that you can use as targets for the "logger" pub package.  Stop using print() and start using logger.info()
homepage: https://github.com/chrisbu/logging_handlers
environment:
  sdk: '>=0.8.7'

dependencies:
  intl: any 
  web_ui: any 
  polymer: any
  logging: any 

dev_dependencies:
  unittest: any 
  browser: any 
