name: logging_handlers
version: 0.6.1
authors: 
  Chris Buckett <chrisbuckett@gmail.com>
  Günter Zöchbauer <guenter@gzoechbauer.com>
description: A selection of handlers that you can use as targets for the "logger" pub package.  Stop using print() and start using logger.info()
homepage: https://github.com/chrisbu/logging_handlers
environment:
  sdk: any #'>=0.5.0+1.r21823'

dependencies:
  intl: any #0.5.0+1
  web_ui: any #0.4.6+2
  polymer: any
  logging: any #0.5.0+1

dev_dependencies:
  unittest: any #0.5.0+1
  browser: any #'>=0.5.0+1'
